### ISSUE TITLE
Help from CliMA

### ISSUE THREAD

**Issue by Sbozzolo** [valentinaschueller/clima-playground#1]
Hi @valentinaschueller, I am Gabriele, from CliMA. 

Our packages are constantly evolving and might be intimitading to use, but we are always excited to work with other people (and improve our codes)! 

If you'd like to use our codes for some research project (or anything else), feel free to let us know and we can help. :)

**Comment by valentinaschueller** [comment]
Thanks, Gabriele! I have been in contact with Julia Sloan about this project already, so I think I am sorted for now. But I will get back to you if necessary!
